# Generated by Django 3.1.7 on 2021-06-10 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opettaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(default='', max_length=100)),
                ('puhelin', models.CharField(default='', max_length=20)),
            ],
            options={
                'ordering': ['nimi'],
            },
        ),
        migrations.CreateModel(
            name='Kurssi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(default='', max_length=100)),
                ('laajuus', models.IntegerField()),
                ('opettaja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.opettaja')),
            ],
            options={
                'ordering': ['nimi'],
            },
        ),
    ]
